# Generated by Django 5.1.6 on 2025-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_nom_member_nomfamille_member_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
