# Generated by Django 5.1.6 on 2025-02-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='motdepasse',
            new_name='mot_de_passe',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='nomfamille',
            new_name='nom_de_famille',
        ),
    ]
